name: Build and Release Python Wheels

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: quay.io/pypa/manylinux_2_34_x86_64

    steps:
      - name: Checkout source code with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Run full build inside single shell
        run: |
          chmod +x ./etc/BuildPythonPackage.sh
          chmod +x ./etc/BuildMultiPythonPackage.sh
          chmod +x ./etc/InstallerConda.sh 
          ./etc/BuildPythonPackage.sh > /dev/null 2>&1
          mkdir build
          cd build
          cmake ..  -DSWIG_EXECUTABLE=/usr/local/bin/swig -DCMAKE_CXX_FLAGS="${CMAKE_CXX_FLAGS} -DBOOST_CSTDFLOAT_NO_LIBQUADMATH_SUPPORT"
          make -j$(nproc)
          cd ..
          ./etc/InstallerConda.sh
      
          source /opt/conda/bin/activate
          conda deactivate
      
          for PY_VER in 3.7 3.8 3.9 3.10 3.11 3.12 3.13; do
            ./etc/BuildMultiPythonPackage.sh $PY_VER || exit 1
          done


      - name: Upload wheels to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: /io/dist/*.whl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
